### ISSUE TITLE
F-droid package

### ISSUE THREAD

**Issue by hayalci** [arpruss/simplestopwatch#1]
Hi, thanks for this great clock/stopwatch. There are a bunch of stopwatch applications in F-droid, but 1) they are too old, installing them gives warnings 2) they look bad, in general 3) there aren't any "giant font" option in any one of them.

Would you consider submitting the Giant Stopwatch to F-droid? https://f-droid.org/en/contribute/

**Comment by arpruss** [comment]
I don't want to register for another site, update on another site, etc. Right now I have to update on github, Google Play and Amazon Appstore. If anybody wants the apk, they can get it from Github.

**Comment by arpruss** [comment]
Also, since it's open source, anybody who wants to upload it is free to do so.

**Comment by hayalci** [comment]
Thanks, I've sent a pull request to fdroid.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8728/
