### ISSUE TITLE
[FR] Reset stopwatch to 0

### ISSUE THREAD

**Issue by another-sapiens** [arpruss/simplestopwatch#5]
Hi there!

At the moment, we have the option to further delay the stopwatch by 3 seconds before starting. However, there's currently not a way of setting it back to 0 once it's delayed, and this could result in being stuck at `–6` or `–9` or any negative number.

An extra `Reset` button for the Stopwatch could be a handy feature.  :)

**Comment by arpruss** [comment]
I don't understand the issue. You just keep pressing delay and it will cycle the delay to zero.

**Comment by another-sapiens** [comment]
Oh!  Nevermind, I stopped pressing it once it reached –9 and didn't know it went back to 0 after that. It's working as intended.
